### ISSUE TITLE
Testing help

### ISSUE THREAD

**Issue by wictorwilen** [MagnusPer/Balboa-GS510SZ#1]
@MagnusPer - if you need a tester/contributor, please share the code. I'm all set with hardware to test this out!

**Comment by MagnusPer** [comment]
Hi there!
First software delivery Phu! Have tested myself a couple of hours and it seems to work as expected so far. Mainly happy case scenario but anyway something is up and running :-)

Try this basic version out and give me some feedback and you are super welcome to contribute.

**Comment by netmindz** [comment]
Great work turning this round so quickly

**Comment by MagnusPer** [comment]
@netmindz - Thank you! Most of it was actually working with the oscilloscope to understand how the logic was connected. The library has now a limited scope of functionality as a start.

**Comment by netmindz** [comment]
You say limited, but from quick look it appeared you had mapped all that the control panel can do.

Only bit that comes to mind for the library would higher level functions like setting a specific temp rather than just +/-

**Comment by MagnusPer** [comment]
That is exactly what I working on now to set a specific temp function instead of "push" the button x number of times

**Comment by wictorwilen** [comment]
If electricity prices is decent this weekend I'll fill up my spa and start testing this! Amazing job so far

**Comment by MagnusPer** [comment]
@wictorwilen - Before filling up the SPA with water you might test the communication working as expected. I can imagine you will have some fault codes in the LCD display such low water etc. But at least you see that it works.

INFO: My top priority on this project is to be able to control when in time during the day the heater should be activated. This in order to save some money to spend on something more funnier:-)

**Comment by netmindz** [comment]
Yeah that's why I want to get write access to my GL series. Have home assistant put into sleep overnight if the weather looks unsuitable the following evening or weekend day
